# Generated by Django 4.1.5 on 2023-02-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="trait",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
