# Generated by Django 4.1.5 on 2023-02-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="scientific_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
